name: flask-ci-workflow

on:
  push:

jobs:
  flask-ci-job:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build Docker Image
        run: docker build -t flask-app:v1.0.0 .

      - name: Run Docker Container
        run: docker run -d --name flask-app-container -p 5000:5000 flask-app:v1.0.0

      - name: Smoke Test
        run: |
          sleep 5
          curl --fail http://localhost:5000/health